version: '3.8'

services:
  # Servicio de health check independiente - ahora será el punto de entrada principal
  health:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python health.py
    ports:
      - "${PORT:-8001}:8001"
    environment:
      - HEALTH_PORT=8001
      - PORT=${PORT:-8001}
    restart: always

  # Servicio de gateway para recibir tráfico
  gateway:
    image: nginx:alpine
    expose:
      - "80"
    volumes:
      - ./railway-nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - PORT=80
    command: /bin/sh -c "envsubst '$$PORT' < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf.tmp && mv /etc/nginx/nginx.conf.tmp /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - RAILWAY_ENVIRONMENT=true
      - DATABASE_URL=${DATABASE_URL}
      - LOYVERSE_API_TOKEN=${LOYVERSE_API_TOKEN}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - ALLOWED_HOSTS=*
      - PORT=8000
      - DEBUG=False
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --workers=2 --threads=4 --timeout=120 --bind 0.0.0.0:8000 config.wsgi:application"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - REACT_APP_API_URL=/api
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped 