# Generated by Django 4.2 on 2025-03-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_detallefactura_porcentaje_ganancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='precio_compra_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='unidades_paquete',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_compra_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_paquete',
            field=models.IntegerField(default=1),
        ),
    ]
