# Generated by Django 4.2 on 2025-03-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_detallefactura_precio_compra_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(max_length=36)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('inventory_levels.update', 'Actualización de niveles de inventario'), ('items.update', 'Actualización de items'), ('customers.update', 'Actualización de clientes'), ('receipts.update', 'Actualización de recibos'), ('shifts.create', 'Creación de turnos')], max_length=25)),
                ('status', models.CharField(choices=[('ENABLED', 'Habilitado'), ('DISABLED', 'Deshabilitado')], default='ENABLED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='ultima_actualizacion_stock',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
