# Generated by Django 4.2 on 2025-03-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_webhook_producto_stock_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
