# Generated by Django 4.2 on 2025-03-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_producto_categoria_producto_categoria_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria_data',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria_id',
        ),
    ]
