# Generated by Django 4.2 on 2025-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_remove_producto_categoria_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fuente_actualizacion',
            field=models.CharField(blank=True, default='loyverse', help_text='Indica la fuente de la última actualización (loyverse, factura)', max_length=50),
        ),
    ]
