# Generated by Django 4.2 on 2025-03-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_producto_fuente_actualizacion'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL para comprobar si la columna existe y crearla solo si no existe
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'facturacion_producto'
                    AND column_name = 'aplicar_iva'
                ) THEN
                    ALTER TABLE facturacion_producto
                    ADD COLUMN aplicar_iva boolean DEFAULT True;
                END IF;
            END
            $$;
            """,
            # Reverse SQL (opcional)
            """
            -- No se elimina la columna, ya que podría existir por otras razones
            """
        ),
    ]
