# Generated by Django 4.2 on 2025-03-23 11:28

from django.db import migrations


class Migration(migrations.Migration):
    """
    Migración vacía para marcar como aplicada ya que los campos ya existen
    en la base de datos.
    """

    dependencies = [
        ('facturacion', '0008_producto_aplicar_iva'),
    ]

    operations = [
        # No hay operaciones - los campos ya existen
    ]
