# Generated by Django 4.2 on 2025-03-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_producto_aplicar_iva_producto_es_precio_variable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_precio_variable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_ganancia',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_base_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_tasa',
            field=models.CharField(default='BCV', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fuente_actualizacion',
            field=models.CharField(default='loyverse', help_text='Indica la fuente de la última actualización (loyverse, factura)', max_length=50),
        ),
    ]
