# Generated by Django 4.2 on 2025-03-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_producto_aplicar_iva_producto_es_precio_variable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='aplicarIva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='precio_base_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='tipo_tasa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
