# Generated by Django 4.2 on 2025-03-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_detallefactura_aplicariva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='unidades_paquete',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
