# Generated by Django 4.2 on 2025-03-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_alter_detallefactura_unidades_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='aplicar_iva',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='variant_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
