# Generated by Django 4.2 on 2025-04-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_add_variant_id_to_producto'),
        ('facturacion', '0013_producto_aplicar_iva_producto_variant_id'),
    ]

    operations = [
    ]
