# Generated by Django 4.2 on 2025-05-11 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0014_merge_20250427_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasacambio',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasas_cambio', to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario'),
            preserve_default=False,
        ),
    ]
