# Generated by Django 4.2 on 2025-05-11 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyverseUserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyverse_user_subject', models.CharField(help_text="Identificador 'sub' único del usuario en Loyverse.", max_length=255, unique=True, verbose_name='Subject ID de Loyverse')),
                ('loyverse_account_name', models.CharField(blank=True, help_text="Nombre del negocio en Loyverse (claim 'name').", max_length=255, null=True, verbose_name='Nombre de Cuenta Loyverse')),
                ('loyverse_email', models.EmailField(blank=True, help_text="Email de la cuenta Loyverse (claim 'email').", max_length=254, null=True, verbose_name='Email Loyverse')),
                ('access_token', django_cryptography.fields.encrypt(models.TextField(verbose_name='Token de Acceso Loyverse (cifrado)'))),
                ('refresh_token', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='Token de Refresco Loyverse (cifrado)'))),
                ('token_type', models.CharField(default='Bearer', max_length=50, verbose_name='Tipo de Token')),
                ('expires_at', models.DateTimeField(help_text='Fecha y hora de expiración del access_token.', verbose_name='Fecha de Expiración del Token')),
                ('scope', models.TextField(help_text='Scopes concedidos por el usuario, separados por espacio.', verbose_name='Alcance (Scopes)')),
                ('is_active', models.BooleanField(default=False, help_text='Indica si la conexión y los tokens son actualmente válidos y utilizables.', verbose_name='Conexión Activa')),
                ('last_token_refresh_time', models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización de Token')),
                ('last_error_message', models.TextField(blank=True, null=True, verbose_name='Último Mensaje de Error')),
                ('price_sync_status', models.CharField(choices=[('IDLE', 'Idle'), ('QUEUED', 'Queued'), ('SYNCING', 'Syncing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with Errors'), ('FAILED', 'Failed'), ('TOKEN_INVALID', 'Token Invalid')], default='IDLE', help_text='Estado de la última sincronización de precios', max_length=30, verbose_name='Estado de Sincronización de Precios')),
                ('last_price_sync_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Inicio Última Sinc. Precios')),
                ('last_price_sync_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin Última Sinc. Precios')),
                ('last_price_sync_details', models.JSONField(blank=True, help_text='Resumen o detalles de la última sincronización (ej. productos actualizados/fallidos).', null=True, verbose_name='Detalles Última Sinc. Precios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyverse_connection', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de BodegaClick')),
            ],
            options={
                'verbose_name': 'Conexión de Usuario Loyverse',
                'verbose_name_plural': 'Conexiones de Usuarios Loyverse',
                'ordering': ['-created_at'],
            },
        ),
    ]
